<a href="https://colab.research.google.com/github/Suryan5h/MachineLearning_Projects/blob/main/PCA/change_of_basis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [23]:
M=np.array([[1,-2],[1,1]]).T
M

array([[ 1,  1],
       [-2,  1]])

In [24]:
M=np.linalg.inv(M)
M

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [25]:
M @ np.array([-3,12])

array([-5.,  2.])